### ISSUE TITLE
Updating to version 2.0.0 and above results in HTTP 500 Error

### ISSUE THREAD

**Issue by mike-source** [soberwp/controller#89]
I can load the front-end of my site normally locally (on MAMP with PHP 7.2.1) and soberwp/controller version 2.0.1, but when I tried to deploy onto SiteGround hosting (PHP 7.2.5) I got a HTTP 500 Error.

After troubleshooting I found that when using "soberwp/controller": "9.0.0-beta.4" via composer instead, the site loads as it should.

I am getting the following in the PHP error log on the server with versions 2.0.0+:

```
PHP Fatal error: Uncaught ReflectionException: Class App\Controllers\FrontPage does not exist in /web/app/themes/sage/vendor/soberwp/controller/src/Loader.php:119
Stack trace:
#0 /web/app/themes/sage/vendor/soberwp/controller/src/Loader.php(119): ReflectionClass->__construct('App\\Controllers...')
#1 /web/app/themes/sage/vendor/soberwp/controller/src/Loader.php(49): Sober\Controller\Loader->setClassesAlias()
#2 /web/app/themes/sage/vendor/soberwp/controller/controller.php(22): Sober\Controller\Loader->__construct(Object(Brain\Hierarchy\Hierarchy))
#3 /web/wp/wp-includes/class-wp-hook.php(286): Sober\Controller\loader('')
#4 /web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /web/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /web/wp/wp-settings.php(450): do_action('init')
#7 /web/wp-config.php(9): requ in /home/u00000/sage9/web/app/themes/sage/vendor/soberwp/controller/src/Loader.php on line 119
```

Any ideas?

**Comment by mike-source** [comment]
never mind! It was fixed in this issue: https://github.com/soberwp/controller/issues/75#issuecomment-380134629

(see last post)
